- name: "Deploy with Ansible"
  hosts: cat
  connection: local
  gather_facts: true
  become: true
  become_user:  "{{ lookup('env', 'USER') }}"
  environment:
    http_proxy: http://proxy.cat.com:80
    https_proxy: http://proxy.cat.com:80
  vars:
    ansible_user: paynen3
    ansible_group: users

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  roles:
    - role: markosamuli.pyenv
      # had to put here to apt install dependencies but keep global user as me
      become_user: root 
      tags:
        - core
        - pyenv
  tasks:
    - include: tasks/core.yml
    - include: tasks/repos.yml
    - include: tasks/python-setup.yml
    - include: tasks/stow.yml
    - include: tasks/desktop.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml


