- name: "Deploy with Ansible"
  hosts: all
  connection: local
  gather_facts: true
  become: true
  become_user:  "{{ lookup('env', 'USER') }}"
  # uncomment for work
  environment:
    http_proxy: http://proxy.cat.com:80
    https_proxy: http://proxy.cat.com:80

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  # vars:
  #   user: "{{ ansible_user_id }}"

  roles:
    - role: markosamuli.pyenv
      # had to put here to apt install dependencies but keep global user as me
      become_user: root 
      tags:
        - core
        - pyenv
  tasks:
    - include: tasks/core.yml
    - include: tasks/repos.yml
    - include: tasks/python-setup.yml
    - include: tasks/stow.yml
    - include: tasks/desktop.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml


