- name: "Deploy with Ansible"
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    ansible_group: nic
    ansible_user: nic
  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

    - name: update repositories
      apt: 
        update_cache: true
        force_apt_get: true
        state: present
      become: true
      changed_when: False

  roles:
    - role: markosamuli.pyenv
      # had to put here to apt install dependencies but keep global user as me
      become_user: root 
      tags:
        - core
        - pyenv
    # - role: monolithprojects.homebrew
    #   become_user: root
    #   tags:
    #     - try_brew
  tasks:
    - import_tasks: tasks/core.yml
      tags: core
    - import_tasks: tasks/node-setup.yml
      tags: node
    - import_tasks: tasks/cargo.yml
      tags: cargo
    - import_tasks: tasks/stow.yml
      tags: stow
    - import_tasks: tasks/zsh-setup.yml
      tags: zsh
    - import_tasks: tasks/repos.yml
      tags: repos
    - import_tasks: tasks/python-setup.yml
      tags: python
    - import_tasks: tasks/desktop.yml
      tags: desktop
    - import_tasks: tasks/nvim-setup.yml
      tags: nvim
