---
roles:
  - name: markosamuli.pyenv
    # version: v5.0.0
  - name: geerlingguy.ruby
  # - name: suzuki-shunsuke.pyenv-module
  - name: markosamuli.ansible-linuxbrew
  - name: monolithprojects.homebrew
