- name: Install System Packages required for nvim
  # become_user: root
  become: true
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  apt:
    name: 
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - libncurses5-dev
      - g++
      - python-dev
      - python3-dev
      - python3-pip
      - ruby
      - ruby-dev

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/third-party/neovim"
    update: yes
    version: v0.7.0
  ignore_errors: yes
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Build neovim
  become_user: root
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && sudo make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Install neovim
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && sudo make install"
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Check if pynvim venv3 exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv3"
  register: pynvim_venv3_exists
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Create pynvim3 environment 
  when: pynvim_venv3_path.stat.islnk is not defined
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  shell: |
    cd {{ lookup('env', 'HOME') }}/.config/nvim/
    python3 -m venv .venv3  --prompt nvim3

- name: Install pynvim into venv3
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  pip:
    name: pynvim
    virtualenv: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv3"
    virtualenv_command: python3 -m venv

- name: Check if pynvim venv2 exists
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv2"
  register: pynvim_venv2_exists

- name: Install neovim venv2
  when: pynvim_venv2_path.stat.islnk is not defined
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  shell: |
    cd {{ lookup('env', 'HOME') }}/.config/nvim/
    virtualenv -p /usr/bin/python .venv2  --prompt nvim2

- name: Install pynvim into venv2
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  pip:
    name: pynvim
    virtualenv: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv2"

# - name: Neovim Plugin Development 1
#   become_user: root
#   apt: name=luarocks
#   tags:
#     - install
#     - terminal
#     - neovim
#     - nvim

# - name: Neovim Plugin Development 2 luacheck
#   shell: luarocks install luacheck
#   become_user: root
#   tags:
#     - install
#     - terminal
#     - neovim
#     - nvim

- name: Install Vim-Plug
  shell: curl -fLo {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Install vim Plugins
  ignore_errors: yes
  shell: nvim -u ~/.config/nvim/plugins.vim +PlugInstall +qall
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim

- name: install python lsp
  when: pylsp_path.stat.islnk is not defined
  tags:
    - lsp
    - python-lsp
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  block:
  - name: Setup python-lsp-server
    shell: pipx install 'python-lsp-server[all]' --force

  - name: Setup pylsp-mypy
    shell: pipx inject python-lsp-server pylsp-mypy --force

  - name: Setup jedi-language-server
    shell: pipx install jedi-language-server --force

- name: check is yaml-language-server installed
  shell: command -v yaml-language-server
  register: yamllsp_exists
  ignore_errors: yes
  tags:
    - lsp
    - yaml-lsp
    - nvim

- name: Setup yaml language server
  when: yamllsp_path.stat.islnk is not defined
  shell: npm i -g yaml-language-server@latest
  tags:
    - lsp
    - yaml-lsp

- name: check is bashlsp installed
  shell: command -v bash-language-server
  register: bashlsp_exists
  ignore_errors: yes
  tags:
    - lsp
    - bash-lsp
    - nvim

- name: Setup bash language server
  when: bashlsp_path.stat.islnk is not defined
  shell: npm i -g bash-language-server@latest
  tags:
    - lsp
    - bash-lsp
    - nvim

- name: Setup jedi-language-server
  shell: pipx install jedi-language-server --force
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp

- name: Setup black 
  shell: pipx install "black==20.8b1" --force
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp

- name: Setup flake8 
  shell: pipx install flake8 --force
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp

- name: Setup isort 
  shell: pipx install isort --force
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp

- name: Install pyflyby 
  shell: pipx install pyflyby --force 
  tags:
    - install
    - python
    - dotfiles
    - nvim
