- name: Change pyenv permissions
  become_user: root
  file:
    state   : directory
    recurse : yes
    path: "{{ pyenv_root }}" 
    owner: "{{ ansible_user}}"
    group: "{{ ansible_group}}"
  tags:
    - pyenv
    - permissions
    - core
    - install

- name: Set default Python to 3.8
  shell: pyenv global "{{ pyenv_python38_version }}"
  tags:
    - pyenv
    - python
    - install 


- name: Install cookiecutter 
  shell: pipx install cookiecutter --force 
  tags:
    - install
    - python
    - dotfiles
    - nvim

- name: Install pyflyby 
  shell: pipx install pyflyby --force 
  tags:
    - install
    - python
    - dotfiles
    - nvim
