- name: ensure personal git directory
  file:
    path: "{{ lookup('env', 'HOME') }}/personal"
    state: directory
  tags:
    - repos

- name: ensure work directory
  file:
    path: "{{ lookup('env', 'HOME') }}/work"
    state: directory
  tags:
    - repos

- name: ensure third-party directory
  file:
    path: "{{ lookup('env', 'HOME') }}/third-party"
    state: directory
  tags:
    - repos

- name: Clone Find Kedro
  ansible.builtin.git:
    repo: 'https://github.com/WaylonWalker/find-kedro.git'
    dest: "{{ lookup('env', 'HOME') }}/third-party/find-kedro"
    update: no

