- name: ensure dotfiles directory
  file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles"
    state: directory
  tags:
    - install
    - terminal
    - core
    - stow
    - dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    # repo: 'git@github.com:nicpayne713/dotfiles.git'
    repo: 'https://github.com/nicpayne713/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    update: no
    recursive: no  # personal needs ssh... not sure what to do about this yet
    single_branch: yes
    version: home
  tags:
    - install
    - terminal
    - core
    - stow
    - dotfiles
- name: stow dotfile
  shell: cd ~/dotfiles && ./ansible-install
  tags:
    - install
    - terminal
    - core
    - stow
    - dotfiles
